- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart smartd
  ansible.builtin.service:
    name: smartd
    state: restarted
